### ISSUE TITLE
Corrupted component which didn't works

### ISSUE THREAD

**Issue by isteric-senior** [nojsja/react-treeview#2]
Current version of component has several errors which forbid its usage.
One of them is fixing by this PR - https://github.com/nojsja/react-treeview/pull/1 - but this PR is not merged.
So, component is abandoned. I recommend just use [Semantic UI's List](https://react.semantic-ui.com/elements/list/) instead of that. List supports nesting.

**Comment by nojsja** [comment]
I fixed this component just now, you can install the new version: react-treeview-semantic@1.0.5, and there is a full [demo](https://github.com/nojsja/react-mobx-template/blob/master/app/views/page1/index.jsx).
